metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - memory
    - network
    - filesystem
    - process
  period: 10s
  processes: ['.*']
  cpu.metrics: ["percentages"]
  process.include_top_n:
    by_cpu: 5
    by_memory: 5
  processors:
    - add_docker_metadata: ~

- module: docker
  metricsets:
    - container
    - cpu
    - diskio
    - healthcheck
    - info
    - memory
    - network
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  processors:
    - add_docker_metadata: ~

output.elasticsearch:
  hosts: ["https://elasticsearch:9200"]
  ssl.certificate_authorities:
    - /usr/share/metricbeat/config/certs/ca/ca.crt

logging.level: info
logging.to_stderr: true
