global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django_app'
    static_configs:
      - targets: [ 'django_app:80' ]

  - job_name: 'ai_inference'
    static_configs:
      - targets: [ 'ai_inference:8099' ]
