name: Deploy to server

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'production-v1'
      url: https://eatingshot.jonngwanma.de
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: create remote directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          # password: ${{ secrets.PASSWORD }}
          script: |
            mkdir -p /home/ubuntu/deployment

      - name: copy source via ssh key
        uses: burnett01/rsync-deployments@master
        with:
          switches: -avzr --delete --exclude 'db_data' --exclude '.env' --exclude 'models' --exclude 'inference_photos' --exclude 'redis_data'
          path: .
          remote_path: /home/ubuntu/deployment
          remote_host: ${{ secrets.HOST }}
          remote_user: ubuntu
          remote_key: ${{ secrets.KEY }}

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            cd /home/ubuntu/deployment
            for volume in caddy_data caddy_config esdata certs; do
              docker volume create $volume
            done
            docker compose down -v --remove-orphans
            docker compose up --build -d
